Friend Module Columns
    Friend Const AbilityAbbreviation = "ability_abbreviation"
    Friend Const AbilityId = "ability_id"
    Friend Const MaximumScore = "maximum_score"
    Friend Const MinimumScore = "minimum_score"
    Friend Const AbilityName = "ability_name"
    Friend Const AbilityScore = "ability_score"
    Friend Const CharacterCount = "character_count"
    Friend Const CharacterId = "character_id"
    Friend Const CharacterName = "character_name"
    Friend Const PlayerId = "player_id"
    Friend Const PlayerName = "player_name"
    Friend Const RaceId = "race_id"
    Friend Const RaceName = "race_name"
End Module
