Friend Module Columns
    Friend Const ColumnAbilityAbbreviation = "ability_abbreviation"
    Friend Const ColumnAbilityId = "ability_id"
    Friend Const ColumnMaximumScore = "maximum_score"
    Friend Const ColumnMinimumScore = "minimum_score"
    Friend Const ColumnAbilityName = "ability_name"
    Friend Const ColumnAbilityScore = "ability_score"
    Friend Const ColumnCharacterCount = "character_count"
    Friend Const ColumnCharacterId = "character_id"
    Friend Const ColumnCharacterName = "character_name"
    Friend Const ColumnPlayerId = "player_id"
    Friend Const ColumnPlayerName = "player_name"
    Friend Const ColumnRaceId = "race_id"
    Friend Const ColumnRaceName = "race_name"
End Module
