Friend Module Columns
    Friend Const AbilityAbbreviation = "ability_abbreviation"
    Friend Const AbilityId = "ability_id"
    Friend Const MaximumScore = "maximum_score"
    Friend Const MinimumScore = "minimum_score"
    Friend Const AbilityName = "ability_name"
    Friend Const AbilityScore = "ability_score"
    Friend Const CharacterCount = "character_count"
    Friend Const CharacterDescription = "character_description"
    Friend Const CharacterId = "character_id"
    Friend Const CharacterName = "character_name"
    Friend Const ClassId = "class_id"
    Friend Const ClassName = "class_name"
    Friend Const DieRoll = "die_roll"
    Friend Const ExperiencePoints = "experience_points"
    Friend Const HitDieSize = "hit_die_size"
    Friend Const Die = "die"
    Friend Const HitPoints = "hit_points"
    Friend Const Level = "level"
    Friend Const MaximumHitDice = "maximum_hit_dice"
    Friend Const PlayerId = "player_id"
    Friend Const PlayerName = "player_name"
    Friend Const RaceClassId = "race_class_id"
    Friend Const RaceId = "race_id"
    Friend Const RaceName = "race_name"
End Module
